import {execFileSync} from 'child_process';
import {readdirSync, writeFileSync} from 'fs';
import {extname, join} from 'path';
import {fileURLToPath} from 'url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const MUSIC_DIR = join(ROOT, 'public', 'music');
const OUTPUT_FILE = join(ROOT, 'src', 'tracks.js');
const AUDIO_EXTENSIONS = new Set(['.mp3', '.wav']);

const files = readdirSync(MUSIC_DIR)
  .filter((name) => AUDIO_EXTENSIONS.has(extname(name).toLowerCase()))
  .sort((a, b) => a.localeCompare(b));

// Duration (seconds) per track, via ffprobe — used by schema.js to reject an
// `audioStartSeconds` that would run past a track's actual end (previously a
// silent failure: the exported clip just went quiet with no explanation).
// If ffprobe isn't installed, duration comes back `null` for every track and
// that validation is skipped rather than blocking sync-tracks entirely.
let ffprobeMissing = false;

const probeDuration = (name) => {
  if (ffprobeMissing) return null;
  try {
    const output = execFileSync(
      'ffprobe',
      ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', join(MUSIC_DIR, name)],
      {encoding: 'utf8'},
    );
    const seconds = parseFloat(output);
    return Number.isFinite(seconds) ? Math.round(seconds * 10) / 10 : null;
  } catch (err) {
    if (err.code === 'ENOENT') {
      ffprobeMissing = true;
      console.warn(
        'ffprobe not found on PATH — skipping track duration checks (install ffmpeg to enable audioStartSeconds range validation).',
      );
    } else {
      console.warn(`Could not read duration of "${name}": ${err.message}`);
    }
    return null;
  }
};

const trackEntries = files.map((name) => {
  const key = name.slice(0, -extname(name).length);
  return {key, file: `music/${name}`, duration: probeDuration(name)};
});

const trackLines = trackEntries.map(
  ({key, file}) => `  ${JSON.stringify(key)}: ${JSON.stringify(file)},`,
);
const durationLines = trackEntries.map(
  ({key, duration}) => `  ${JSON.stringify(key)}: ${duration === null ? 'null' : duration},`,
);

const output = `// AUTO-GENERATED by scripts/generate-tracks.js from public/music/.
// Do not edit by hand — this file is regenerated before every \`npm run
// studio\`/\`npm run render:*\`. Drop an mp3/wav into public/music/ and rerun
// (or just restart Studio) to add it here; the filename (minus extension)
// becomes both the object key and the label shown in Remotion Studio's
// \`track\` dropdown, since Zod enums have no separate display-name field.
export const TRACKS = {
  none: null,
${trackLines.length ? trackLines.join('\n') + '\n' : ''}};

// Duration in seconds per track (via ffprobe), or null if it couldn't be
// read. See schema.js's audioStartSeconds validation.
export const TRACK_DURATIONS = {
${durationLines.length ? durationLines.join('\n') + '\n' : ''}};
`;

writeFileSync(OUTPUT_FILE, output);
console.log(`Wrote ${OUTPUT_FILE} with ${files.length} track(s): ${files.join(', ') || '(none found)'}`);
