// AUTO-GENERATED by scripts/generate-tracks.js from public/music/.
// Do not edit by hand — this file is regenerated before every `npm run
// studio`/`npm run render:*`. Drop an mp3/wav into public/music/ and rerun
// (or just restart Studio) to add it here; the filename (minus extension)
// becomes both the object key and the label shown in Remotion Studio's
// `track` dropdown, since Zod enums have no separate display-name field.
export const TRACKS = {
  none: null,
  "A Mighty Fortress Is Our God": "music/A Mighty Fortress Is Our God.mp3",
  "Am I a Solder of the Cross_": "music/Am I a Solder of the Cross_.mp3",
  "Canticle of the Turning": "music/Canticle of the Turning.mp3",
  "King Alfred's War Song": "music/King Alfred's War Song.mp3",
  "Rise Again Ye Lion-Hearted": "music/Rise Again Ye Lion-Hearted.mp3",
  "The Son of God Goes Forth to War": "music/The Son of God Goes Forth to War.mp3",
  "War Song": "music/War Song.mp3",
  "Watchman's Balad": "music/Watchman's Balad.mp3",
};

// Duration in seconds per track (via ffprobe), or null if it couldn't be
// read. See schema.js's audioStartSeconds validation.
export const TRACK_DURATIONS = {
  "A Mighty Fortress Is Our God": 186.9,
  "Am I a Solder of the Cross_": 182,
  "Canticle of the Turning": 234.9,
  "King Alfred's War Song": 147,
  "Rise Again Ye Lion-Hearted": 184.9,
  "The Son of God Goes Forth to War": 192.7,
  "War Song": 214.4,
  "Watchman's Balad": 513.5,
};
